# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vanishing Point
header-img: img/large-vanishing-point-blu-ray6-1.jpg
email: vncprado@gmail.com
description: "Hey Kowalski, you out there?"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://viniciusprado.org" # the base hostname & protocol for your site
twitter_username: vncprado
github_username:  vncprado
facebook_username: vncprado

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: [jekyll-paginate]

#permalink: "/:title/"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Vincius Prado da Fonseca"

# Build settings
#markdown: kramdown
